image:
  file: .gitpod.Dockerfile
ports:
  - port: 4444
    onOpen: ignore
  - port: 6080
    onOpen: open-preview
tasks:
  - name: install wdio to workspace
    init: |
      npm install
  - name: run tests
    command: |
      gp sync-await
      yes | npm run wdio